DROP TRIGGER "ABSTRACT_MESSAGE_UPDATE_TALK_NUMBER";
DROP TRIGGER "ABSTRACT_MESSAGE_DELETE_TO_CACHE";

DROP TRIGGER "ABSTRACT_MESSAGE_INSERT_FLAT_REFERENCE_WITH_REFERENCE";
DROP TRIGGER "ABSTRACT_MESSAGE_INSERT_FLAT_REFERENCE_WITHOUT_REFERENCE";
DROP TRIGGER "ABSTRACT_MESSAGE_DELETE_FLAT_REFERENCE";

DROP TRIGGER "CLIENT_USER_INFO_INSERT_TO_CACHE";
DROP TRIGGER "CLIENT_USER_INFO_DELETE_TO_CACHE";

DROP TRIGGER "ABSTRACT_MESSAGE_DELETE_DEPENDENCE";
DROP TRIGGER "ABSTRACT_MESSAGE_UPDATE_FLAT_REFERENCE";

DROP TRIGGER "MESSAGE_TOPIC_INSERT_TO_FTS"
DROP TRIGGER "MESSAGE_TOPIC_DELETE_TO_FTS"


DROP TABLE "FLAT_REFERENCE";
DROP TABLE "ABSTRACT_MESSAGE";
DROP TABLE "CLIENT_USER_INFO";
DROP TABLE "MESSAGE_TYPE";
DROP TABLE "FTS_CLIENT_USER_INFO";
DROP TABLE "FTS_ABSTRACT_MESSAGE";
DROP TABLE "FTS_MESSAGE_TOPIC";
DROP TABLE "MESSAGE_TOPIC";
