package org.nearbytalk.http;

public enum ErrorResponse {

	INVALID_CLIENT_USER_INFO, INVALID_REQUEST_TYPE, INVALID_NULL_USER_NAME, INVALID_SHA_1_VALUE, USER_NAME_SPACE_FULL, INVALID_MESSAGE_QUERY, QUERY_FAILED, INVALID_MESSAGE, ACTION_FAILED, MESSAGE_CANNOT_EMPTY, ID_CLASH, INVALID_SEARCH_TYPE, INVALID_ID_BYTES, INVALID_MESSAGE_TYPE, USER_DESCRIPTION_TOO_LONG, SERVER_BUSY, NOT_LOGIN, FILE_TOO_LARGE,
	/**
	 * 
	 * 
	 * 
	 * file upload lacks file part
	 */
	FIELD_INCOMPLETE, BAD_REFERENCE, INVALID_JSON, INVALID_USER_QUERY, INVALID_SEARCH_NAME, INVALID_USER_NAME, DUPLICATE_MESSAGE;

}
